### ISSUE TITLE
Missing Parenthesis?

### ISSUE THREAD

**Issue by TheOneTrueGuy** [pesser/stable-diffusion#10]
Got this error:
Traceback (most recent call last):
  File "/content/latent-diffusion/scripts/txt2img.py", line 10, in <module>
    from ldm.util import instantiate_from_config
  File "/usr/local/lib/python3.7/dist-packages/ldm.py", line 20
    print self.face_rec_model_path 
             ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(self.face_rec_model_path)?

**Comment by litevxx** [comment]
You are not meant to install the ldm module from pip, rather it should be importing it from the folder. Add a sys.path.append to `sys.path.append("path/to/stable-diffusion")` near the start of the file, uninstall ldm from pip and try again.

**Comment by TheOneTrueGuy** [comment]
Thanks!
