### ISSUE TITLE
latent diffusion vs stable diffusion

### ISSUE THREAD

**Issue by johndpope** [pesser/stable-diffusion#17]
for clarity - does this repo actually do stable diffusion? 
it doesn't seem like the models for stable diffusion are available.
or am I mistaken?
https://huggingface.co/CompVis/stable-diffusion/blob/main/README.md

UPDATE
seems like they are interchangable. but....
https://github.com/cfreude/stable-diffusion/commit/7fd86d03fda6e1c0859af7610959c678a89c77a7

**Comment by rromb** [comment]
This is an development repository. Please see [CompVis/stable-diffusion](https://github.com/CompVis/stable-diffusion/) for the Stable Diffusion release.
